### ISSUE TITLE
Support of LSF system for DeePKS built-in dispatcher

### ISSUE THREAD

**Issue by scott-5** [deepmodeling/deepks-kit#55]
As mentioned on the [doc](https://deepks-kit.readthedocs.io/en/latest/inputs-preperation.html#machine-yaml), on a local machine or on a cluster via slurm or PBS, it is recommended to use the DeePKS built-in dispatcher by machine.yaml, but for other schedule system like LSF, built-in dispatcher does not support that.

**Comment by ouqi0711** [comment]
While the built-in dispatcher in DeePKS does not support LSF for now, you may use DPDispatcher for LSF job submission. To do that, you may refer to machine_dpdispatcher.yaml file provided [here](https://github.com/deepmodeling/deepks-kit/tree/abacus/examples/water_single_lda2pbe_abacus/iter). This file is used for job submission on Bohrium/Lebesgue, and can be easily modified for LSF jobs. Helpful tips for modifying  related keywords of this file can be found [here](https://docs.deepmodeling.com/projects/dpdispatcher/en/latest/batch.html#lsf). The documentation of running DeePKS with ABACUS can be found [here](https://deepks-kit.readthedocs.io/en/latest/).

**Comment by scott-5** [comment]
Ok, thx
