### ISSUE TITLE
Unable to Reshape Data Correctly - ValueError: cannot reshape array of size 28800 into shape (40000,8,18)

### ISSUE THREAD

**Issue by Shangguanying992** [deepmodeling/deepks-kit#67]
While running the deepks model, I encountered the following issue:
File "/home/ljcgroup/.conda/envs/deepks/lib/python3.11/site-packages/deepks/model/reader.py", line 79, in prepare
    data_dm = np.load(self.d_path).reshape(raw_nframes, self.natm, self.ndesc)
ValueError: cannot reshape array of size 28800 into shape (40000,8,18)
Upon inspection, it appears that the program generated a file of size (200, 200) named l_e_delta, where e_name=l_e_delta and self.e_path = self.check_exist(e_name+".npy"). The error occurred in reader.py at line 77.data_ec = np.load(self.e_path).reshape(-1, 1) I don't know why this code resulted in an incorrect shape of (40000,1).
I expect the data from l_e_delta.npy to be reshaped to the expected shape of (200, 8, 18). I have also confirmed that the actual size of the l_e_delta.npy file is 28800 elements. Please assist in examining the code in reader.py responsible for ensuring proper data handling and reshaping.

**Comment by Shangguanying992** [comment]
The error file occurred in iter/iter.init/01.train

**Comment by y1xiaoc** [comment]
Thanks for the issue! If I understand correctly the l_e_delta should be (200, 1), which is a single energy value for each frames. That tensor is calculated [here](https://github.com/deepmodeling/deepks-kit/blob/7978b398a5edd688e3fffc3c29f839d3c7b99602/deepks/scf/fields.py#L107C30-L107C30). I guess the (200, 200) comes from a subtraction between (200, 1) and (1, 200) arrays. There might be some bug leads to this undesired broadcasting behavior. To confirm, is the water example running correctly? If so, I think we need to check the shape of your input data.

**Comment by Shangguanying992** [comment]
Thank you for your assistance. The water example is functioning correctly. After your reminder, I checked and found that the issue was due to my input files (energy.npy and force.npy) being directly converted by dpdata without the required format conversion. After adjusting the format, the problem has been resolved. Thanks again.
