### ISSUE TITLE
Poor Convergence in AIMD Dataset Generation with VASP for Abacus Calculation

### ISSUE THREAD

**Issue by Shangguanying992** [deepmodeling/deepks-kit#69]
While generating a dataset for AIMD using VASP and subsequent calculation with Abacus, I encountered the following issues:
Upon setting the lattice constant to 1 in VASP, I received the warning message "!!! WARNING: Some atoms are too close!!!!!! Please check the nearest-neighbour list". Additionally, the convergence was very poor, approximately 0.3.
After realizing that VASP uses Angstrom units, I adjusted the lattice constant to 1.8897259886. However, none of the configurations converged.
Upon inspecting the configurations, I did not notice significant deformations beyond the normal range for molecular dynamics simulations.
I am seeking guidance on addressing these issues to ensure proper convergence.

Additional Context:
Software: VASP 6.3.1, Abacus3.5.3
The water_single example is functioning correctly.

**Comment by jameswind** [comment]
Is this a problem of deepks-kit? Can you give an example of the
configuration? (I suspect this problem should go to ABACUS, though)

**Comment by Shangguanying992** [comment]
My system is transition metal oxides. Maybe you are right and I will go to Abacus to take this issue.
