### ISSUE TITLE
basis function coefficients and exponents

### ISSUE THREAD

**Issue by petrucci86** [deepmodeling/deepks-kit#7]
Dear developers/users,

is there any simple way to print the coefficients and exponents of the gaussian primitive basis functions after a standard DFT single-point calculation? Thanks

**Comment by y1xiaoc** [comment]
Deepks scf calculation is implemented as an extension of pyscf dft class. The basis is stored in the pyscf mol object. You may check their examples for more information. Fir example https://github.com/pyscf/pyscf/blob/master/examples/gto/04-input_basis.py and https://github.com/pyscf/pyscf/blob/master/examples/gto/11-basis_info.py
